export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const PROCESS_SUCESS = "PROCESS_SUCESS";
export const PROJECT_SUCESS = "PROJECT_SUCESS";
export const EQUIPMENT_SUCESS = "EQUIPMENT_SUCESS";
export const EQUIPMENT_SUCESSC = "EQUIPMENT_SUCESSC";
